### ISSUE TITLE
The performance of VAR Tokenizer

### ISSUE THREAD

**Issue by youngsheen** [FoundationVision/VAR#16]
What is the performance of VAR tokenizer? As it is trained on OpenImages while some other VQGAN tokenizers are trained on ImageNet only. I wonder the gain of performance brought by the pre-trained data.

**Comment by keyu-tian** [comment]
hi @youngsheen, more VQVAE evals are coming in the next paper update.

We trained VQVAE on OpenImages refer to VQGAN (see https://github.com/CompVis/taming-transformers?tab=readme-ov-file#overview-of-pretrained-models).

We actually found training vqvae directly on ImageNet yields slightly better results than OpenImages. We kept using OpanImages to stay aligned with our VQGAN baseline.

**Comment by luohao123** [comment]
Does the tokenizer able to do understanding?

**Comment by huxiaotaostasy** [comment]
I use vqvae in var, and the image produced by encoding and decoding is compared with the original image as follows.
![image](https://github.com/FoundationVision/VAR/assets/33438526/3cdaaf16-0564-4b5b-a743-188e9240b5ce)
![image](https://github.com/FoundationVision/VAR/assets/33438526/ccf86141-558a-4d42-a0af-09353bccc7d9)
Is this because the generalization performance of vqvae is not good enough?

**Comment by keyu-tian** [comment]
@huxiaotaostasy please make sure you denormalize and clamp the output of VQVAE `out` by `out = out.mul(0.5).add_(0.5).clamp_(0, 1)`.

**Comment by keyu-tian** [comment]
@luohao123 maybe you can create token maps (r1, r2, ..., rK) by repeating an index in [0, V-1] on all scales and then decode them to see how's the reconstructed image like.

**Comment by Jot-De** [comment]
@huxiaotaostasy Did the [fix] solve the issue?
